#ifndef SOURCE_ST_STM32L152RE_NUCLEO_BLINKY_CUSTOMLIBRARY_ASCIILIB_H_
#define SOURCE_ST_STM32L152RE_NUCLEO_BLINKY_CUSTOMLIBRARY_ASCIILIB_H_

#include <string.h>
#define  ASCII_8X16_System

void GetASCIICode(unsigned char* pBuffer,unsigned char ASCII);


#endif /* SOURCE_ST_STM32L152RE_NUCLEO_BLINKY_CUSTOMLIBRARY_ASCIILIB_H_ */
