#ifndef SOURCE_ST_STM32L152RE_NUCLEO_BLINKY_CUSTOMLIBRARY_HZLIB_H_
#define SOURCE_ST_STM32L152RE_NUCLEO_BLINKY_CUSTOMLIBRARY_HZLIB_H_

#include <string.h>

void GetGBKCode(unsigned char* pBuffer,unsigned char * c);

#endif /* SOURCE_ST_STM32L152RE_NUCLEO_BLINKY_CUSTOMLIBRARY_HZLIB_H_ */
